server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:flight_db
    username: sa
    password: 
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Automatically create the DDLs
    # hibernate.ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: false
    # show-sql: true
  sql:
    init:
      mode: embedded
      platform: h2    

